version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
      commands:
        - aws s3 sync dist/ s3://emoto-crosses
        - aws configure set preview.cloudfront true
        - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION --paths "/*"
cache:
  paths:
    - node_modules/**/*
